"""v2: observation tree, tenancy, scores

Revision ID: 1983f984a553
Revises: 
Create Date: 2026-09-11 12:18:56.735344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1983f984a553'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingestion_dead_letters',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.Column('event_id', sa.String(), nullable=True),
    sa.Column('stream_message_id', sa.String(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_dlq_project_created', 'ingestion_dead_letters', ['project_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('retention_days', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_projects_name')
    )
    op.create_table('api_keys',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('public_key', sa.String(), nullable=False),
    sa.Column('hashed_secret_key', sa.String(), nullable=False),
    sa.Column('display_secret_key', sa.String(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hashed_secret_key', name='uq_api_keys_hashed_secret'),
    sa.UniqueConstraint('public_key', name='uq_api_keys_public_key')
    )
    op.create_index('ix_api_keys_project', 'api_keys', ['project_id'], unique=False)
    op.create_table('dataset_items',
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('dataset_id', sa.String(), nullable=False),
    sa.Column('input', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('expected_output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_trace_id', sa.String(), nullable=True),
    sa.Column('source_observation_id', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'ARCHIVED', name='dataset_item_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'id')
    )
    op.create_index('ix_dataset_items_project_dataset', 'dataset_items', ['project_id', 'dataset_id'], unique=False)
    op.create_index('ix_dataset_items_source_trace', 'dataset_items', ['source_trace_id'], unique=False)
    op.create_table('dataset_run_items',
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('dataset_run_id', sa.String(), nullable=False),
    sa.Column('dataset_item_id', sa.String(), nullable=False),
    sa.Column('trace_id', sa.String(), nullable=False),
    sa.Column('observation_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'id'),
    sa.UniqueConstraint('project_id', 'dataset_run_id', 'dataset_item_id', name='uq_run_item_once_per_run')
    )
    op.create_index('ix_run_items_project_run', 'dataset_run_items', ['project_id', 'dataset_run_id'], unique=False)
    op.create_index('ix_run_items_trace', 'dataset_run_items', ['project_id', 'trace_id'], unique=False)
    op.create_table('dataset_runs',
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('dataset_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'id'),
    sa.UniqueConstraint('project_id', 'dataset_id', 'name', name='uq_dataset_run_name')
    )
    op.create_index('ix_dataset_runs_project_dataset', 'dataset_runs', ['project_id', 'dataset_id'], unique=False)
    op.create_table('datasets',
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'id'),
    sa.UniqueConstraint('project_id', 'name', name='uq_dataset_project_name')
    )
    op.create_table('evaluation_rules',
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('evaluator_id', sa.String(), nullable=False),
    sa.Column('target', sa.Enum('TRACE', 'DATASET_RUN_ITEM', name='eval_target'), nullable=False),
    sa.Column('filter', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sampling_rate', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('sampling_rate >= 0 AND sampling_rate <= 1', name='ck_eval_rule_sampling_range'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'id')
    )
    op.create_index('ix_eval_rules_project_active', 'evaluation_rules', ['project_id', 'is_active'], unique=False)
    op.create_table('evaluator_versions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('evaluator_id', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('model_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('variable_mapping', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('score_name', sa.String(), nullable=False),
    sa.Column('score_data_type', sa.Enum('NUMERIC', 'CATEGORICAL', 'BOOLEAN', name='score_data_type'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('evaluator_id', 'version', name='uq_evaluator_version')
    )
    op.create_index('ix_evaluator_versions_project', 'evaluator_versions', ['project_id', 'evaluator_id'], unique=False)
    op.create_table('evaluators',
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'id'),
    sa.UniqueConstraint('project_id', 'name', name='uq_evaluator_project_name')
    )
    op.create_table('job_executions',
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('evaluator_version_id', sa.String(), nullable=False),
    sa.Column('rule_id', sa.String(), nullable=True),
    sa.Column('trace_id', sa.String(), nullable=True),
    sa.Column('observation_id', sa.String(), nullable=True),
    sa.Column('dataset_run_item_id', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'ERROR', 'CANCELLED', name='job_status'), nullable=False),
    sa.Column('score_id', sa.String(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('judge_latency_ms', sa.Float(), nullable=True),
    sa.Column('judge_cost', sa.Numeric(precision=18, scale=12), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'id')
    )
    op.create_index('ix_jobs_project_run_item', 'job_executions', ['project_id', 'dataset_run_item_id'], unique=False)
    op.create_index('ix_jobs_project_status', 'job_executions', ['project_id', 'status'], unique=False)
    op.create_index('ix_jobs_project_trace', 'job_executions', ['project_id', 'trace_id'], unique=False)
    op.create_table('models',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('match_pattern', sa.String(), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tokenizer_id', sa.String(), nullable=True),
    sa.Column('tokenizer_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_models_project_name', 'models', ['project_id', 'model_name'], unique=False)
    op.create_table('score_configs',
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('data_type', sa.Enum('NUMERIC', 'CATEGORICAL', 'BOOLEAN', name='score_data_type'), nullable=False),
    sa.Column('min_value', sa.Float(), nullable=True),
    sa.Column('max_value', sa.Float(), nullable=True),
    sa.Column('categories', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'id'),
    sa.UniqueConstraint('project_id', 'name', name='uq_score_config_project_name')
    )
    op.create_table('traces',
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('input', sa.Text(), nullable=True),
    sa.Column('output', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('release', sa.String(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('is_experiment', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'id')
    )
    op.create_index('ix_traces_metadata', 'traces', ['metadata'], unique=False, postgresql_using='gin')
    op.create_index('ix_traces_project_session', 'traces', ['project_id', 'session_id'], unique=False)
    op.create_index('ix_traces_project_timestamp', 'traces', ['project_id', sa.literal_column('timestamp DESC')], unique=False)
    op.create_index('ix_traces_project_user', 'traces', ['project_id', 'user_id'], unique=False)
    op.create_index('ix_traces_tags', 'traces', ['tags'], unique=False, postgresql_using='gin')
    op.create_table('observations',
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('trace_id', sa.String(), nullable=False),
    sa.Column('parent_observation_id', sa.String(), nullable=True),
    sa.Column('type', sa.Enum('SPAN', 'GENERATION', 'EVENT', 'AGENT', 'TOOL', 'CHAIN', 'RETRIEVER', 'EMBEDDING', 'GUARDRAIL', name='observation_type'), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completion_start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('latency_ms', sa.Float(), sa.Computed('EXTRACT(EPOCH FROM (end_time - start_time)) * 1000', persisted=True), nullable=True),
    sa.Column('time_to_first_token_ms', sa.Float(), sa.Computed('EXTRACT(EPOCH FROM (completion_start_time - start_time)) * 1000', persisted=True), nullable=True),
    sa.Column('level', sa.Enum('DEBUG', 'DEFAULT', 'WARNING', 'ERROR', name='observation_level'), nullable=False),
    sa.Column('status_message', sa.Text(), nullable=True),
    sa.Column('input', sa.Text(), nullable=True),
    sa.Column('output', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('provided_model_name', sa.String(), nullable=True),
    sa.Column('internal_model_id', sa.String(), nullable=True),
    sa.Column('model_parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('provided_usage_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('usage_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('provided_cost_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cost_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('total_cost', sa.Numeric(precision=18, scale=12), nullable=True),
    sa.Column('prompt_name', sa.String(), nullable=True),
    sa.Column('prompt_version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('end_time IS NULL OR end_time >= start_time', name='ck_obs_end_after_start'),
    sa.ForeignKeyConstraint(['internal_model_id'], ['models.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'id')
    )
    op.create_index('ix_obs_metadata', 'observations', ['metadata'], unique=False, postgresql_using='gin')
    op.create_index('ix_obs_project_model', 'observations', ['project_id', 'provided_model_name'], unique=False)
    op.create_index('ix_obs_project_parent', 'observations', ['project_id', 'parent_observation_id'], unique=False)
    op.create_index('ix_obs_project_trace', 'observations', ['project_id', 'trace_id'], unique=False)
    op.create_index('ix_obs_project_type_start', 'observations', ['project_id', 'type', sa.literal_column('start_time DESC')], unique=False)
    op.create_table('prices',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('model_id', sa.String(), nullable=False),
    sa.Column('usage_type', sa.String(), nullable=False),
    sa.Column('price', sa.Numeric(precision=24, scale=18), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_id', 'usage_type', name='uq_price_model_usage')
    )
    op.create_table('scores',
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('trace_id', sa.String(), nullable=True),
    sa.Column('observation_id', sa.String(), nullable=True),
    sa.Column('dataset_run_item_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('data_type', sa.Enum('NUMERIC', 'CATEGORICAL', 'BOOLEAN', name='score_data_type'), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('string_value', sa.String(), nullable=True),
    sa.Column('source', sa.Enum('API', 'EVAL', 'ANNOTATION', name='score_source'), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('config_id', sa.String(), nullable=True),
    sa.Column('evaluator_version_id', sa.String(), nullable=True),
    sa.Column('author_user_id', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(data_type = 'CATEGORICAL' AND string_value IS NOT NULL) OR (data_type <> 'CATEGORICAL' AND value IS NOT NULL)", name='ck_scores_value_matches_type'),
    sa.CheckConstraint('(trace_id IS NOT NULL)::int + (dataset_run_item_id IS NOT NULL)::int = 1', name='ck_scores_exactly_one_anchor'),
    sa.ForeignKeyConstraint(['evaluator_version_id'], ['evaluator_versions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'id')
    )
    op.create_index('ix_scores_project_name_ts', 'scores', ['project_id', 'name', sa.literal_column('timestamp DESC')], unique=False)
    op.create_index('ix_scores_project_observation', 'scores', ['project_id', 'observation_id'], unique=False)
    op.create_index('ix_scores_project_run_item', 'scores', ['project_id', 'dataset_run_item_id'], unique=False)
    op.create_index('ix_scores_project_trace', 'scores', ['project_id', 'trace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_scores_project_trace', table_name='scores')
    op.drop_index('ix_scores_project_run_item', table_name='scores')
    op.drop_index('ix_scores_project_observation', table_name='scores')
    op.drop_index('ix_scores_project_name_ts', table_name='scores')
    op.drop_table('scores')
    op.drop_table('prices')
    op.drop_index('ix_obs_project_type_start', table_name='observations')
    op.drop_index('ix_obs_project_trace', table_name='observations')
    op.drop_index('ix_obs_project_parent', table_name='observations')
    op.drop_index('ix_obs_project_model', table_name='observations')
    op.drop_index('ix_obs_metadata', table_name='observations', postgresql_using='gin')
    op.drop_table('observations')
    op.drop_index('ix_traces_tags', table_name='traces', postgresql_using='gin')
    op.drop_index('ix_traces_project_user', table_name='traces')
    op.drop_index('ix_traces_project_timestamp', table_name='traces')
    op.drop_index('ix_traces_project_session', table_name='traces')
    op.drop_index('ix_traces_metadata', table_name='traces', postgresql_using='gin')
    op.drop_table('traces')
    op.drop_table('score_configs')
    op.drop_index('ix_models_project_name', table_name='models')
    op.drop_table('models')
    op.drop_index('ix_jobs_project_trace', table_name='job_executions')
    op.drop_index('ix_jobs_project_status', table_name='job_executions')
    op.drop_index('ix_jobs_project_run_item', table_name='job_executions')
    op.drop_table('job_executions')
    op.drop_table('evaluators')
    op.drop_index('ix_evaluator_versions_project', table_name='evaluator_versions')
    op.drop_table('evaluator_versions')
    op.drop_index('ix_eval_rules_project_active', table_name='evaluation_rules')
    op.drop_table('evaluation_rules')
    op.drop_table('datasets')
    op.drop_index('ix_dataset_runs_project_dataset', table_name='dataset_runs')
    op.drop_table('dataset_runs')
    op.drop_index('ix_run_items_trace', table_name='dataset_run_items')
    op.drop_index('ix_run_items_project_run', table_name='dataset_run_items')
    op.drop_table('dataset_run_items')
    op.drop_index('ix_dataset_items_source_trace', table_name='dataset_items')
    op.drop_index('ix_dataset_items_project_dataset', table_name='dataset_items')
    op.drop_table('dataset_items')
    op.drop_index('ix_api_keys_project', table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_table('projects')
    op.drop_index('ix_dlq_project_created', table_name='ingestion_dead_letters')
    op.drop_table('ingestion_dead_letters')
    # ### end Alembic commands ###
    # Autogenerate does not drop Postgres enum types; without this, re-running
    # upgrade after a downgrade fails with DuplicateObject.
    for enum_name in (
        'dataset_item_status', 'eval_target', 'job_status', 'observation_level',
        'observation_type', 'score_data_type', 'score_source',
    ):
        op.execute(f'DROP TYPE IF EXISTS {enum_name}')
